settings:
  positive-sound: "ENTITY_PLAYER_LEVELUP"
  negative-sound: "BLOCK_ANVIL_BREAK"
  winner-cooldown: 1440 #In minutes
  actionbar:
    enabled: true
    refresh: 2 #Ticks
  enabled-worlds:
    overworld:
      world-name: "world"
      treasure-block: ENDER_CHEST
      treasure-particles: COMPOSTER
      treasure-animation: "orb" #none, spiral, orb
      treasure-icon: EMERALD #Only if DecentHolograms is not installed
      require-all-mobs-dead: true
      allow-pvp-near-treasure: false
      allow-flight-near-treasure: false
      allow-god-near-treasure: false
      allow-elytra-near-treasure: false
      flare-type: "many" #Options: none, few, many
      flare-particle: COMPOSTER
      fireworks: true
      delay: 200 #In ticks
      chance-for-treasure: 20
      min-players-online: 15
      reward-all-players-who-participated: false
      distance-from-player-to-spawn-mobs: 0 #0 To spawn when the treasure spawns, other value to spawn when the distance is achieved
      interval: 30
      duration: 20
      cooldown: 15
      mobs:
        - "ZOMBIE:5"
        - "SKELETON:5"
        - "SPIDER:3"
      item-rewards:
        - "DIAMOND:6"
        - "EMERALD:1"
      command-rewards:
        - "eco give %player% 100"