settings:
  positive-sound: "ENTITY_PLAYER_LEVELUP"
  negative-sound: "BLOCK_ANVIL_BREAK"
  allow-pvp-near-treasure: false
  allow-flight-near-treasure: false
  allow-god-near-treasure: false
  allow-elytra-near-treasure: false
  disable-griefing-protection: false
  protection-radius: 50 #The radius in which the griefing protection works. ATTENTION! You should NOT set this to 0!
  min-players-online: 15 #Minimum players to have a chance to spawn a treasure
  protect-mobs-from-sun: true #Should zombies not set on fire from the sun?
  potion-effect-radius: 20 #How close you need to be to the treasure in order to be affected by the potion effects
  broadcast-to-all-worlds: false #Send the actionbar message to all the worlds. If multiple treasures are started only one treasure will appear in the actionbar.
  winner-cooldown: 1440 #How long in minutes, a treasure winner has to wait before claiming another treasure
  fall-protection:
    duration: 1200
    level: 2
  actionbar:
    enabled: true
    refresh: 2 #Refresh rate in ticks
  blacklisted-commands:
    - "heal"
  blacklisted-biomes:
    - "COLD_OCEAN"
    - "DEEP_OCEAN"
    - "DEEP_DARK"
    - "DEEP_FROZEN_OCEAN"
    - "DEEP_LUKEWARM_OCEAN"
    - "FROZEN_OCEAN"
    - "FROZEN_RIVER"
    - "ICE_SPIKES"
    - "LUKEWARM_OCEAN"
    - "OCEAN"
    - "RIVER"
  effects-particles: #You should change these only if they cause compatibility issues.
    dust: DUST
    wax_off: WAX_OFF
    soul: SOUL
    soul-fire-flame: SOUL_FIRE_FLAME
    warped-spore: WARPED_SPORE
    crit: CRIT
    lava: LAVA
    flame: FLAME
    treasure-spawn-particle: EXPLOSION
    treasure-fall-particle: CAMPFIRE_SIGNAL_SMOKE
    treasure-remove-particle: EXPLOSION_EMITTER
  updater: true
  bstats: true
