settings:
  positive-sound: "ENTITY_PLAYER_LEVELUP"
  negative-sound: "BLOCK_ANVIL_BREAK"
  winner-cooldown: 1440 #How long in minutes, a treasure winner has to wait before claiming another treasure
  actionbar:
    enabled: true
    refresh: 2 #Refresh rate in ticks
  enabled-worlds:
    overworld:
      world-name: "world"
      treasure-block: ENDER_CHEST
      treasure-particles: COMPOSTER
      treasure-animation: "protection" #none, spiral, orb, protection / Protection only works if 'require-all-mobs-dead' is 'true'
      treasure-icon: EMERALD #Only if DecentHolograms is not installed
      require-all-mobs-dead: true #Can a player claim a treasure if they haven't defeated the mobs yet?
      allow-pvp-near-treasure: false
      allow-flight-near-treasure: false
      allow-god-near-treasure: false
      allow-elytra-near-treasure: false
      flare-type: "many" #Options: none, few, many
      flare-particle: COMPOSTER
      fireworks: true #Spawn fireworks upon clicking the treasure
      max-treasure-distance: 15000 #Bypasses the border setting, if the border is 20k, and this is 15k, the max distance for the treasure will be 15k. Usefull for when you don't set your border
      delay: 200 #In ticks, the delay from the announcement that the treasure will spawn until it really spawns.
      chance-for-treasure: 20 #The chance to spawn a random treasure
      min-players-online: 15 #Minimum players to have a chance to spawn a treasure
      reward-all-players-who-participated: false #Reward all players who killed a treasure keeper?
      distance-from-player-to-spawn-mobs: 0 #0 To spawn when the treasure spawns, other value to spawn when the distance is achieved
      mob-wandering-distance: 40 #How far away the mobs can wander before being teleported back near the treasure
      animate-mob-spawning: true #If distance-from-player-to-spawn-mobs is more than 0, play an animation to the mobs when they spawn?
      interval: 30 #Interval of time in minutes for a chance to spawn the treasure (ex. every 30mins you have 20% chance for the treasure to spawn)
      duration: 20 #The duration of the treasure before it despawns
      cooldown: 15 #Cooldown between treasures in minutes
      protect-mobs-from-sun: true #Should zombies not set on fire from the sun?
      potion-effect-radius: 20 #How close you need to be to the treasure in order to be affected by the potion effects
      potion-effects:
        - "REGENERATION:1"
      mobs:
        - "ZOMBIE:5"
        - "SKELETON:5"
        - "SPIDER:3"
      item-rewards:
        - "DIAMOND:6"
        - "EMERALD:1"
      command-rewards:
        - "eco give %player% 100"
  effects-particles: #You should change these only if they cause compatibility issues.
    dust: DUST
    wax_off: WAX_OFF
    soul: SOUL
    soul-fire-flame: SOUL_FIRE_FLAME
    warped-spore: WARPED_SPORE
    crit: CRIT
    lava: LAVA
    flame: FLAME
    treasure-spawn-particle: EXPLOSION
    treasure-fall-particle: CAMPFIRE_SIGNAL_SMOKE
    treasure-remove-particle: EXPLOSION_EMITTER
