###############################################################################
#
# 💎 MYSTIC TREASURES
#       BY MOSHULIKA
#
###############################################################################
main: com.Moshu.Main
name: MysticTreasures
version: 3.1
description: The world is full of treasures!
author: Moshu
website: mc.b-zone.ro
softdepend: [Vault, WorldGuard, ChunkyBorder, EssentialsX, Citizens, LuckPerms, MythicMobs, ItemsAdder, Oraxen, DecentHolograms, FancyHolograms, Nexo, ProtocolLib, MMOItems, packetevents, Lands]
api-version: "26.2"

commands:
  hunt:
    description: "Interact with the plugin"

permissions:
  mystictreasures.hunt:
    default: true
    description: Use the main command
  mystictreasures.admin:
    default: op
  mystictreasures.bypass:
    default: op