##########################################
#                                        #
#                HEADER                  #
#                                        #
##########################################

main: com.Moshu.Main
name: MysticTreasures
version: 2.1
description: The world is full of treasures!
author: Moshu
website: mc.b-zone.ro
softdepend: [Vault, WorldGuard, ChunkyBorder, EssentialsX, Citizens, LuckPerms, MythicMobs, ItemsAdder, Oraxen, DecentHolograms, FancyHolograms]
api-version: "1.13"

commands:
  hunt:
    description: "Interact with the plugin"


permissions:
  mystictreasures.hunt:
    default: true
    description: Use the main command
  mystictreasures.admin:
    default: op
  mystictreasures.bypass:
    default: op