##########################################
#                                        #
#                HEADER                  #
#                                        #
##########################################

main: com.Moshu.Main
name: MysticTreasures
version: 27.07.2024
description: The world is full of treasures!
author: Moshu
website: mc.b-zone.ro
softdepend: [Vault, WorldGuard, ChunkyBorder, EssentialsX, Citizens, LuckPerms]
api-version: "1.21"

commands:
  hunt:
    permission: mystictreasures.hunt


permissions:
  mysticturfs.hunt:
    default: op
    description: Use the main command